name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Workflow
    name: WorkFlow
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's Gradle Build
      - name: Build
      - uses: actions/setup-java@v1
          with:
            java-version: 1.11
      - name: Gradle Build
        run: echo 'Build ${{ gradlew build }}.'